name: beverage_app
description: A new Flutter project.

publish_to: 'none'
version: 3.0.1+11
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^5.0.2
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lottie: ^1.2.1
  razorpay_flutter: ^1.3.4
  shimmer: ^2.0.0
  upgrader: ^4.11.1
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4

flutter_icons:
  image_path: "assets/images/logo.png"
  # name: 'Beverage App'
  ios: false
  android: true

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
